# MD001/heading-increment/header-increment - Heading levels should
# only increment by one level at a time
MD001: false

# MD013/line-length - Line length
MD013:
  # Number of characters
  line_length: 88

# MD024/no-duplicate-heading/no-duplicate-header - Multiple headings with the same content
MD024:
  # Allow multiple headings with the same content
  siblings_only: true

# MD033/no-inline-html - Inline HTML
MD033: false

# MD036/no-emphasis-as-heading/no-emphasis-as-header - Emphasis used
# instead of a heading
MD036: false

# MD040/fenced-code-language - Fenced code blocks should have a
# language specified
MD040: false

# MD045/no-alt-text - Images should have alternate text (alt text)
MD045: false

# MD046/code-block-style - Code block style
MD046:
  style: "consistent"

# MD051/link-fragments - Link fragments should be valid. Fails on
# quartos #sec style links
MD051: false

ignores: ["explainaboard/third_party"]
