name: pgip
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools>=1.17
  - bedtools
  - csvtk
  - cyvcf2
  - d4tools
  - gatk4
  - gawk
  - mosdepth
  - msprime
  - pyslim
  - samtools
  - slim>=4.0
  - tskit>=0.5.0
  - pip:
      - sgkit[vcf]
