name: pgip
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # - bcftools
  - bokeh>=3.0
  - ca-certificates
  - click
  - cyvcf2
  - demesdraw
  # - gatk4
  # - ipykernel
  # - bash_kernel
  - jupyter
  # - matplotlib
  - msprime>=1.0
  # - networkx
  - openssl
  - pandas
  # - pip
  # - plink
  - pyslim
  - python=3.10
  # - r-animation
  # - r-codetools
  # - r-dotenv
  # - r-gganimate
  # - r-ggplot2
  # - r-gifski
  # - r-igraph
  # - r-irkernel
  - r-jsonlite
  # - r-magick
  # - r-patchwork
  # - r-pdftools
  - r-reticulate
  - r-rmarkdown
  # - r-viridis
  - samtools
  # - scikit-learn
  # - scikit-allel
  - sgkit=0.5.0
  - slim>=4.0
  - tskit>=0.5.0
  # - tqdm
  # - yarl
