name: pgip-dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-lock
  - pip
  - pre-commit
  - r-docopt
  - r-languageserver
  - r-lintr
  - r-precommit
  - pip:
      - editorconfig-checker
