channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools
  - demes
  - demesdraw
  - gatk4
  - ipykernel
  - bash_kernel
  - jupyter-book>=0.13.0
  - jupytext==1.13.8
  - matplotlib
  - msprime>=1.0
  - myst-nb==0.13.2
  - networkx
  - numpy
  - pip
  - plink
  - r-irkernel
  - r-reticulate
  - samtools
  - scikit-learn
  - scikit-allel
  - sphinx
  - tskit>=0.4
  - tqdm
  - yarl
