name: pgip
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools
  - bedtools
  - bokeh>=3.0
  - ca-certificates
  # - click
  - csvtk
  - cyvcf2
  - demesdraw
  - d4tools
  # - gatk4
  - jupyter
  - jupyter-cache
  # - matplotlib
  - mosdepth
  - msprime>=1.0
  # - networkx
  - openssl
  - pandas
  # - plink
  - pyslim
  - python=3.10
  # - r-animation
  - r-codetools
  - r-devtools
  - r-dt
  # - r-dotenv # Must be installed via R
  - r-formatr
  - r-gganimate
  - r-ggplot2
  - r-gifski
  - r-igraph
  # - r-irkernel
  - r-jsonlite
  # - r-magick
  - r-patchwork
  - r-pdftools
  - r-readr
  - r-readxl
  - r-reticulate
  - r-rmarkdown>=2.19
  - r-tidyr
  - r-transformr
  - r-viridis
  - samtools
  # - scikit-learn
  # - scikit-allel
  - sgkit=0.5.0
  - slim>=4.0
  - tskit>=0.5.0
  # - tqdm
  # - yarl
