channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools
  - bokeh
  - demes
  - demesdraw
  - gatk4
  - ipykernel
  - bash_kernel
  - jupyter-book
  - matplotlib
  - msprime>=1.0
  - networkx
  - numpy
  - pip
  - plink
  - r-irkernel
  - r-reticulate
  - scikit-allel
  - sphinx
  - tskit>=0.4
  - tqdm
