name: pgip
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools>=1.17
  - bedtools
  - csvtk
  - gawk
  - mosdepth
  - msprime
  - pyslim
  - samtools
  - sgkit>=0.6.0
  - slim>=4.0
  - tskit>=0.5.0
