name: pgip
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools>=1.17
  - bedtools
  - csvtk
  - cyvcf2
  - d4tools
  - gatk4
  - gawk
  - mosdepth
  - msprime>=1.2
  - pip
  - pyslim
  - python-newick
  - samtools
  - slim>=4.0
  - tskit>=0.5.0
