project:
  type: website
  title: "Population genomics in practice"
  output-dir: _site
  execute-dir: project
  pre-render:
    - ../scripts/prepare.py
    - ../scripts/setup-data.sh
  render:
    - "*.qmd"
    - "!lectures/*.qmd"

website:
  title: "Population genomics in practice"
  navbar:
    logo: assets/logos/nbislogo-green.svg
    left:
      - text: "Slides"
        href: "slides/index.qmd"
      - text: "Exercises"
        file: "exercises/index.qmd"
      - text: "Code recipes"
        file: "recipes/index.qmd"
    right:
      - text: "HOME"
        href: "index.qmd"
      # - text: "CONTENTS"
      #   href: "contents.qmd"
      # - text: "PROGRAM"
      #   href: "program.qmd"
      - text: ABOUT
        href: "about.qmd"
      - icon: "twitter"
        href: "https://twitter.com/NBISwe"
  page-footer:
    border: false
    left: "2023 [NBIS](about.html) | [GPL-3 License](https://choosealicense.com/licenses/gpl-3.0/)"
    right: "Published with [Quarto](https://quarto.org/) v<?quarto.version?>"
  favicon: assets/logos/nbislogo-green.svg

  sidebar:
    - title: "Information"
      contents:
        - index.qmd
        - about.qmd
        - schedule.qmd
        - references.qmd

    - title: "Lecture notes"
      style: "docked"
      contents:
        - "lectures/index.qmd"
        - section: "Monday 8 May"
          contents:
            - "lectures/datageneration.qmd"

    - title: "Slides"
      contents:
        - "slides/index.qmd"
        - section: "Monday 8 May"
          contents:
            - "slides/introduction/index.qmd"
            - file: "slides/pgip/index.qmd"
              text: "What is population genomics?"
            - file: "slides/foundations/index.qmd"
              text: "Foundations"
            - file: "slides/data_generation/index.qmd"
              text: "Variant data generation"
        - section: "Tuesday 9 May"
          contents:
            - "slides/recap_day1/index.qmd"
            - file: "slides/genetic_diversity/index.qmd"
              text: "Genetic diversity"
            - file: "slides/ld_and_recombination/index.qmd"
              text: "Linkage disequilibrium and recombination"
            - file: "slides/population_structure/index.qmd"
              text: "Population structure"
            - file: "slides/admixture/index.qmd"
              text: "Population admixture"
        - section: "Wednesday 10 May"
          contents:
            - "slides/recap_day2/index.qmd"
            - file: "slides/demography/index.qmd"
              text: "Demographic inference"
        - section: "Thursday 11 May"
          contents:
            - "slides/recap_day3/index.qmd"
            - file: "slides/direct_selection/index.qmd"
              text: "Direct selection"
            - file: "slides/linked_selection/index.qmd"
              text: "Linked selection"
        - section: "Friday 12 May"
          contents:
            - "slides/recap_day4/index.qmd"

    - title: "Exercises"
      contents:
        - "exercises/index.qmd"
        - "exercises/preparation.qmd"
        - "exercises/data.qmd"
        - section: "Monday 8 May"
          contents:
            - file: "exercises/popgen_primer/index.qmd"
              text: "Population genetics primer"
            - file: "exercises/variant_calling/index.qmd"
              text: "Variant calling basics"
            - file: "exercises/data_filtering/index.qmd"
              text: "Filtering of resequencing data"
            - file: "exercises/gl/index.qmd"
              text: "Genotype likelihoods and low coverage data"
        - section: "Tuesday 9 May"
          contents:
            - file: "exercises/genetic_diversity/index.qmd"
              text: "Estimating genetic diversity"
            - file: "exercises/ld_and_phasing/index.qmd"
              text: "Linkage disequilibrium and phasing"
            - file: "exercises/fst_divergence/index.qmd"
              text: "Population differentiation"
            - file: "exercises/ld_pruning/index.qmd"
              text: "LD pruning and PCA"
            - file: "exercises/admixture/index.qmd"
              text: "Admixture"
        - section: "Wednesday 10 May"
          contents:
            - file: "exercises/fstatistics/index.qmd"
              text: "D/f statistics"
            - file: "exercises/msmc/index.qmd"
              text: "MSMC"
        - section: "Thursday 11 May"
          contents:
            - file: "exercises/direct_selection/index.qmd"
              text: "Direct selection"
            - file: "exercises/linked_selection/index.qmd"
              text: "Linked selection"

format:
  html:
    theme:
      - cosmo
      - assets/nbis.scss
    toc: true
    embed-resources: true
    date: last-modified
    date-format: "DD-MMM-YYYY"
    lightbox:
      match: auto
  revealjs:
    quarto-required: ">=1.2.269"
    toc: true
    toc-depth: 1
    slide-level: 3
    slide-number: true
    preview-links: true
    chalkboard: true
    smaller: false
    highlight-style: gruvbox
    fig-cap-location: top
    fig-align: left
    fig-height: 12
    fig-width: 10
    width: 1280
    height: 720
    margin: 0.1
    date: last-modified
    date-format: "DD-MMM-YYYY"
    navigation-mode: vertical
    institute: NBIS
    bibliography: assets/bibliography.bib
    csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
    reference-location: margin
    title-slide-attributes:
      data-background-image: assets/logos/nbis-scilifelab.svg
      data-background-size: 500px
      data-background-position: top left
    theme:
      - white
      - assets/nbis.scss

from: markdown+emoji

execute:
  freeze: auto
  cache: true
  echo: true
  warning: false
  include: true
  autodep: true
  eval: true
  error: true

knitr:
  opts_chunk:
    code-fold: false
    tidy: true
    comment-char: "#>"
    fig-format: svg
    engine.opts:
      dvisvgm.opts: --font-format=woff
      template: ../assets/www/tikzfig.tex

jupyter:
  kernelspec:
    name: "pgip"
    language: "python"
    display_name: "Python 3"

filters:
  - lightbox
  - fontawesome
