project:
  type: website
  #type: book
  title: "Population genomics in practice"
  output-dir: _site
  execute-dir: file
  pre-render:
    - prepare.py

execute:
  freeze: auto
  cache: true

bibliography: resources/bibliography.bib
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl

website:
#book:
  title: "Population genomics in practice"
  # chapters:
  #   - index.qmd
  navbar:
    logo: img/nbislogo-green.svg
    left:
      - text: "Lecture notes"
        file: "lectures/index.qmd"
      - text: "Slides"
        file: "slides/index.qmd"
      - text: "Exercises"
        file: "exercises/index.qmd"
      - text: "Code recipes"
        file: "recipes/index.qmd"
  sidebar:
    - title: "Information"
      contents:
        - index.qmd
        - about.qmd
        - schedule.qmd
        - references.qmd

    - title: "Lecture notes"
      style: "docked"
      contents:
        - "lectures/index.qmd"
        - section: "Monday 8 May"
          contents:
            - "lectures/datageneration.qmd"

    - title: "Slides"
      contents:
        - "slides/index.qmd"
        - section: "Monday 8 May"
          contents:
            - "slides/introduction.qmd"
            - "slides/population_genomics_in_practice.qmd"
            - "slides/population_genetics_foundations.qmd"
            - "slides/datageneration.qmd"
        - section: "Tuesday 9 May"
          contents:
            - "slides/genetic_diversity.qmd"
        - section: "Thursday 11 May"
          contents:
            - "slides/selection.qmd"

    - title: "Exercises"
      contents:
        - "exercises/index.qmd"
        - "exercises/preparation.qmd"
        - "exercises/data.qmd"
        - section: "Monday 8 May"
          contents:
            - "exercises/variantfiltering.qmd"
        - section: "Tuesday 9 May"
        - section: "Wednesday 10 May"
          contents:
            - "exercises/ld_pruning_pca.qmd"

  page-footer:
    left: |
      Copyright NBIS
    right: |
      This book was built with <a
      href="https://quarto.org/">Quarto</a>.
  favicon: img/nbislogo-green.svg



format:
  html:
    theme:
      - cosmo
      - nbis.scss
    css: styles.css
    toc: true
    embed-resources: true
  # pdf:
  #   documentclass: scrreport


jupyter:
  kernelspec:
    name: "pgip"
    language: "python"
    display_name: "Python 3"
