name: build

on:
  pull_request:
  push:
    branches: [main]
    tags:
      - '*'

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: cache-conda
      uses: actions/cache@v3
      env:
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yaml') }}

    - name: install miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        mamba-version: "*"
        channels: conda-forge,bioconda,defaults
        channel-priority: true
        environment-file: environment.yaml
        use-only-tar-bz2: true

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install python dependencies
      run: |
        python -m 'pip' install -r requirements.txt
        python -m 'pip' install -e .

    - name: Install pgip and bash jupyter kernels
      run: |
        python -m bash_kernel.install
        python -m ipykernel install --user --name pgip --display-name "Population Genomics in Practice (Python)"

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        tinytex: true

    - name: Publish to GitHub Pages
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        target: gh-pages
        path: docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Copy exercises data
    #   run: |
    #     cp ./requirements.txt ./docs/_site/.
    #     cp -r data ./docs/_site/data
    #     ls data > ./docs/_site/data/files.txt

    # # Push the book's HTML to github-pages
    # - name: GitHub Pages action
    #   if: github.ref == 'refs/heads/main'
    #   uses: peaceiris/actions-gh-pages@v3.5.9
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./docs/_site
